module.exports = {
    SIGN_IN_SUCCESS : '로그인 성공',
    INVALID_PW : '잘못된 비밀번호 입니다.',
    INVALID_USER : '존재하지 않는 아이디입니다.',
    ALREADY_EXIST : '이미 존재하는 회원입니다. ',
    SIGN_UP_FAIL : '회원가입 실패',
    SIGN_UP_SUCCESS : '회원가입 성공',
    LIST_SUCCESS : '데이터 불러오기 성공',
    LIST_FAIL : '데이터 불러오기 실패',
    MISS_DATA : '필요한 데이터 누락',
    POST_FAIL : '게시물 작성 오류',
    POST_SUCCESS : '게시물 작성 성공',
    INVALID_DATE : '유효하지 않은 날짜',
    REQUEST_FAIL : '신청 실패',
    REQUEST_SUCCESS : '신청 성공',
    INVALID_REQUEST : '마감되었거나 신청 권한이 없습니다.',
    APPROVAL_SUCCESS : '요청 처리 성공',
    APPROVAL_FAIL : '요청 처리 실패',
    UNAUTHORIZED: '유효하지 않은 토큰',
    TOKEN_EXPIRED: '토큰 만료',
    GET_USER_INFO_SUCCESS: '유저 정보 확인 성공',
    INVALID_USER : '유효하지 않은 사용자',
    PROFILE_UPDATE_SUCCESS : '프로필 수정 성공',
    PROFILE_UPDATE_FAIL : '프로필 수정 실패',
    DELETE_USER_SUCCESS: '회원 탈퇴 성공',
    INTERNAL_SERVER_ERROR : '서버 에러'
}